name: Python CI

on: #trigger
  push: # event (push, delete, etc)
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    #1
    - name: check out code    
    - uses: actions/checkout@v2 
    #2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    #3
        - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    #4
    - name: run tests
      run: pytest
